# Generated by Django 6.0 on 2026-01-03 21:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="category_image"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="product_image"
            ),
        ),
    ]
